//! Keeps the user book (`docs/user`) in step with the code: the reference pages generated
//! from it, and the pages that must name every interactive command and command-line
//! option.
//!
//! A generated page is committed; its test fails when the file differs from what the
//! generator produces now. To rewrite the files instead:
//!
//! ```text
//! TAGENT_UPDATE_USER_DOCS=1 cargo test -p tagent-cli user_docs
//! ```
//!
//! The book lives outside this package, so a copy built from crates.io has no
//! `docs/user`; the tests then pass without checking anything.

use std::fmt::Write as _;
use std::path::PathBuf;

use tagent::languages::LANGUAGES;
use tagent::providers::{
    dictionary_providers, speech_providers, translation_providers, ProviderDescriptor,
};

use crate::config::{self, Config, HELP_OPTIONS};
use crate::interactive::SLASH_COMMANDS;

/// Set to `1` to rewrite the generated pages instead of checking them.
const UPDATE_VAR: &str = "TAGENT_UPDATE_USER_DOCS";

/// What `history_file` shows in the generated template: the real default is a path on the
/// machine that runs the generator.
const HISTORY_FILE_PLACEHOLDER: &str = "<data folder>/tagent-cli/translation_history.txt";

/// The book's page sources, `docs/user/src`, or `None` outside the repository.
fn book_src() -> Option<PathBuf> {
    let dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../docs/user/src");
    if dir.is_dir() {
        Some(dir)
    } else {
        eprintln!("{} not found; user book checks skipped", dir.display());
        None
    }
}

/// A page of the book, line endings normalized (a Windows checkout may have `\r\n`).
fn read_page(src: &std::path::Path, page: &str) -> String {
    let path = src.join(page);
    std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()))
        .replace("\r\n", "\n")
}

/// Checks (or, with [`UPDATE_VAR`], rewrites) the generated page `page` against `expected`.
fn check_generated(page: &str, expected: &str) {
    let Some(src) = book_src() else { return };
    let path = src.join(page);
    if std::env::var(UPDATE_VAR).is_ok_and(|v| v == "1") {
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(&path, expected).unwrap();
        return;
    }
    let actual = std::fs::read_to_string(&path)
        .unwrap_or_default()
        .replace("\r\n", "\n");
    assert!(
        actual == expected,
        "docs/user/src/{page} is out of date; regenerate it with \
         `{UPDATE_VAR}=1 cargo test -p tagent-cli user_docs`"
    );
}

/// The `tagent-cli.toml` a new install gets, with a fixed target language and a
/// placeholder history path so it doesn't depend on the machine.
fn config_template() -> String {
    config::render_config(&Config {
        target_language: "en".to_string(),
        history_file: HISTORY_FILE_PLACEHOLDER.to_string(),
        ..Config::default()
    })
}

/// One provider kind as the registry describes it on each axis it serves.
struct Kind {
    name: &'static str,
    /// `(axis, display name)` per axis the kind serves.
    axes: Vec<(&'static str, &'static str)>,
    /// The descriptors of those axes, in axis order.
    descriptors: Vec<&'static ProviderDescriptor>,
}

/// Every provider kind in registry order (translation, then dictionary, then speech).
fn kinds() -> Vec<Kind> {
    let mut kinds: Vec<Kind> = Vec::new();
    let axes = [
        ("translation", translation_providers()),
        ("dictionary", dictionary_providers()),
        ("speech", speech_providers()),
    ];
    for (axis, descriptors) in axes {
        for descriptor in descriptors {
            let index = match kinds.iter().position(|k| k.name == descriptor.name) {
                Some(index) => index,
                None => {
                    kinds.push(Kind {
                        name: descriptor.name,
                        axes: Vec::new(),
                        descriptors: Vec::new(),
                    });
                    kinds.len() - 1
                }
            };
            kinds[index].axes.push((axis, descriptor.display_name));
            kinds[index].descriptors.push(descriptor);
        }
    }
    kinds
}

/// A table cell: no line breaks, `|` escaped.
fn cell(text: &str) -> String {
    text.replace('\n', " ").replace('|', "\\|")
}

/// The provider options reference: one section per kind, with its options (the union over
/// its axes, in registry order) and the built-in prompts.
fn provider_options_page() -> String {
    let mut out = String::from(
        "<!-- Generated by tagent-cli's user_docs tests from tagent's provider registry; \
         don't edit. -->\n",
    );
    for kind in kinds() {
        let transport = kind.descriptors[0].transport;
        let jobs: Vec<String> = kind
            .axes
            .iter()
            .map(|(axis, display)| format!("{axis} ({display})"))
            .collect();
        let _ = write!(
            out,
            "\n## `{}`\n\nJobs: {}.\n\n| Option | Required | Default | Description |\n\
             |--------|:--------:|---------|-------------|\n",
            kind.name,
            jobs.join(", ")
        );
        let mut seen: Vec<&str> = Vec::new();
        let mut prompts: Vec<(&str, &str)> = Vec::new();
        for spec in kind.descriptors.iter().flat_map(|d| d.options.iter()) {
            if seen.contains(&spec.key) {
                continue;
            }
            seen.push(spec.key);
            let default = match (spec.key, spec.default) {
                ("timeout_secs", _) => transport.timeout.as_secs().to_string(),
                ("max_retries", _) => transport.max_retries.to_string(),
                (_, Some(text)) if spec.multiline => {
                    prompts.push((spec.key, text));
                    "built in, below".to_string()
                }
                (_, Some(value)) => format!("`{}`", cell(value)),
                (_, None) => "—".to_string(),
            };
            let secret = if spec.secret { " (secret)" } else { "" };
            let _ = writeln!(
                out,
                "| `{}`{secret} | {} | {default} | {} |",
                spec.key,
                if spec.required { "yes" } else { "" },
                cell(spec.description)
            );
        }
        for (key, text) in prompts {
            let _ = write!(
                out,
                "\nThe built-in `{key}`:\n\n```text\n{}\n```\n",
                text.trim_end()
            );
        }
    }
    out
}

/// The supported languages table, from `tagent::languages::LANGUAGES`.
fn languages_page() -> String {
    let mut out = String::from(
        "<!-- Generated by tagent-cli's user_docs tests from tagent::languages::LANGUAGES; \
         don't edit. -->\n\n| Code | Language |\n|------|----------|\n",
    );
    for language in LANGUAGES {
        let _ = writeln!(out, "| `{}` | {} |", language.code, language.name);
    }
    out
}

/// Whether `page` names `token` as code: `` `token` `` or `` `token <args>` ``.
fn names_as_code(page: &str, token: &str) -> bool {
    page.contains(&format!("`{token}`")) || page.contains(&format!("`{token} "))
}

#[test]
fn config_template_page_is_current() {
    check_generated("reference/generated/tagent-cli.toml", &config_template());
}

#[test]
fn provider_options_page_is_current() {
    check_generated(
        "reference/generated/provider-options.md",
        &provider_options_page(),
    );
}

#[test]
fn languages_page_is_current() {
    check_generated("reference/generated/languages.md", &languages_page());
}

#[test]
fn every_interactive_command_is_documented() {
    let Some(src) = book_src() else { return };
    let page = read_page(&src, "cli/interactive-commands.md");
    let missing: Vec<&str> = SLASH_COMMANDS
        .iter()
        .copied()
        .filter(|command| !names_as_code(&page, command))
        .collect();
    assert!(
        missing.is_empty(),
        "docs/user/src/cli/interactive-commands.md doesn't name {missing:?}"
    );
}

#[test]
fn every_command_line_option_is_documented() {
    let Some(src) = book_src() else { return };
    let page = read_page(&src, "reference/command-line.md");
    let missing: Vec<&str> = HELP_OPTIONS
        .iter()
        .flat_map(|(flags, _)| flags.split(", "))
        .filter(|flag| !names_as_code(&page, flag))
        .collect();
    assert!(
        missing.is_empty(),
        "docs/user/src/reference/command-line.md doesn't name {missing:?}"
    );
}

#[test]
fn generated_template_has_no_machine_specific_values() {
    let template = config_template();
    assert!(template.contains(HISTORY_FILE_PLACEHOLDER));
    assert!(template.contains("target_language = \"en\""));
}

#[test]
fn provider_options_page_lists_every_kind_and_option() {
    let page = provider_options_page();
    for descriptor in translation_providers()
        .iter()
        .chain(dictionary_providers())
        .chain(speech_providers())
    {
        assert!(page.contains(&format!("## `{}`", descriptor.name)));
        for spec in descriptor.options {
            assert!(page.contains(&format!("| `{}`", spec.key)), "{}", spec.key);
        }
    }
}
