[package]
name = "tagent-gui"
version = "0.13.0"
edition = "2021"
description = "Tagent GUI — cross-platform text translator with Slint"
publish = false
readme = "README.md"
build = "build.rs"

[[bin]]
name = "tagent-gui"
path = "src/main.rs"

[dependencies]
tagent = { path = "../tagent" }
dirs = "5.0"
slint = "1"
tokio = { version = "1", features = ["full"] }

[build-dependencies]
slint-build = "1"
